<?php
$title = 'Dodaj nowy album';
$this->headTitle($title);
?>
<h1>
    <i class="material-icons" style="font-size:38px;">account_box</i>
    <span><?= $this->escapeHtml($title) ?></span>
</h1>
<?php
echo $error ? '<div class="alert alert-danger" role="alert">Invalid data in form!</div>' : '';
?>
<?php
$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($form->get('name')) ?>
    <?= $this->formElement($form->get('name')) ?>
    <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'list-unstyled alert alert-warning']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('firstname')) ?>
    <?= $this->formElement($form->get('firstname')) ?>
    <?= $this->formElementErrors()->render($form->get('firstname'), ['class' => 'list-unstyled alert alert-warning']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('lastname')) ?>
    <?= $this->formElement($form->get('lastname')) ?>
    <?= $this->formElementErrors()->render($form->get('lastname'), ['class' => 'list-unstyled alert alert-warning']) ?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();